config/routes.rb
Rails.application.routes.draw do
	
		get '/articles', to: 'articles#index', as: 'articles'
		post '/articles', to: 'articles#create'
		get '/articles/new', to: 'articles#new', as: 'new_article'
		get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
		get '/articles/:id', to: 'articles#show', as: 'article'
		put 'articles/:id', to: 'articles#update'
		patch 'articles/:id', to: 'articles#update'
		delete 'articles/:id', to: 'articles#destroy'
			
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>
<ul>
	<% @articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
		</li>
	<% end %>
</ul>
<%= link_to "Create a New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>Create A New Article</h1>
<%= form_for @article do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>
	<%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.body %></p>
<%= link_to "<< Back to All Articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>